{% set version = '1.2-4' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-doe.base
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DoE.base_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DoE.base/DoE.base_{{ version }}.tar.gz
  sha256: c072c01eb59c997100306a1df6e2a2bfd4ad3d993e2d4156f59016123e8de053

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
    - r-combinat
    - r-conf.design
    - r-lattice
    - r-numbers
    - r-partitions
    - r-vcd
  run:
    - r-base
    - r-mass
    - r-combinat
    - r-conf.design
    - r-lattice
    - r-numbers
    - r-partitions
    - r-vcd

test:
  commands:
    - $R -e "library('DoE.base')"           # [not win]
    - "\"%R%\" -e \"library('DoE.base')\""  # [win]

about:
  home: https://prof.bht-berlin.de/groemping/DoE/, https://prof.bht-berlin.de/groemping/
  license: GPL-2.0-or-later
  summary: Creates full factorial experimental designs and designs based on orthogonal arrays
    for (industrial) experiments. Provides diverse quality criteria. Provides utility
    functions for the class design, which is also used by other packages for designed
    experiments.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - tobiasraabe

# Package: DoE.base
# Title: Full Factorials, Orthogonal Arrays and Base Utilities for DoE Packages
# Version: 1.2-4
# Depends: R (>= 2.10), grid, conf.design
# Imports: stats, utils, graphics, grDevices, vcd, combinat, MASS, lattice, numbers, partitions
# Suggests: FrF2, DoE.wrapper, RColorBrewer
# Date: 2023-10-17
# Authors@R: c(person("Ulrike", "Groemping", role = c("aut", "cre"), email = "ulrike.groemping@bht-berlin.de"), person("Boyko", "Amarov", role = "ctb"), person("Hongquan", "Xu", role = "ctb"))
# Description: Creates full factorial experimental designs and designs based on orthogonal arrays for (industrial) experiments. Provides diverse quality criteria. Provides utility functions for the class design, which is also used by other packages for designed experiments.
# License: GPL (>= 2)
# LazyLoad: yes
# LazyData: yes
# Encoding: UTF-8
# URL: https://prof.bht-berlin.de/groemping/DoE/, https://prof.bht-berlin.de/groemping/
# NeedsCompilation: no
# Maintainer: Ulrike Groemping <ulrike.groemping@bht-berlin.de>
# Author: Ulrike Groemping [aut, cre], Boyko Amarov [ctb], Hongquan Xu [ctb]
# Packaged: 2023-11-14 16:23:55 UTC; Gromping
# Repository: CRAN
# Date/Publication: 2023-11-14 19:40:02 UTC
